config/routes.rb
Rails.application.routes.draw do

    root 'articles#index'
    

    resources :articles, except: [:destroy] do
        resources :comments#, only: [:create]
    end
    delete 'articles/:id/delete' => 'articles#destroy', as: 'articles_delete'
    get '/articles/:id/delete' => 'articles#destroy'

    resources :tags

    devise_for :users, controllers: {
        registrations: 'users/registrations'
    }


    get 'my_profile' => 'users#show', as: 'users_show'

end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    belongs_to :user
   


    def tag_list
        self.tags.collect do |tag|
            tag.name
          end.join(", ")
    end
    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    end
    
    def next
        if self == Article.last
            self
        else
            b = self.id
        Article.find(b+1)
            end
       
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, except: [:index,:show]
    def index
        @article= Article.all
    end

    def show
        @article = Article.find(params[:id])
       
        
    end
    
    def new
       @article = current_user.articles.build

    end

    def create
        
            @article = current_user.articles.build(params.require(:article).permit(:title, :body, :note, :tag_list))#.except(:tags))
            # create_or_delete_article_tags(@article,params[:article][:tags])


           if @article.save
            
                redirect_to articles_path
           else 
                render "new" , status: :unprocessable_entity
           end
      
    end

    def edit
        @article = Article.find(params[:id])

    end

    def update
        @article= Article.find(params[:id])
        @article.update(params.require(:article).permit(:title, :body, :note, :tag_list,))
        redirect_to articles_path

    end

    def destroy

        @article= Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    
    end

end

private

# def create_or_delete_article_tags(article,tags)
#    # article.taggings.destroy_all
#     @tags = tags.strip.split(',')
#     @tags.each do |tag|
#         article.tags << Tag.find_or_create_by(name: tag)
#     end
# end

app/views/articles/_error.html.erb
<% if @article.errors.any?%>
<h3>Unable to Save. Error Found !</h4>
    <% @article.errors.full_messages.each do |e|%>
    <%= e %> <br/>
    <%end%>
<%end%>

app/views/articles/_form.html.erb
<div>
    <%= form_with(model: @article) do |f| %> 
        <%= f.label :title %>
        <%= f.text_field :title %> <br/>
        <%= f.label :Body %>
        <%= f.text_area :body %> <br/> <br/>
        <%= f.label :tag_list %><br />
        <%= f.text_field :tag_list,  placeholder: "Separated by Comma (,)"%>
        <%= f.submit %> <br/>
    <% end %>
</div>

app/views/articles/edit.html.erb
<div>
    <h2>Article Edit Form</h2><br/>

    <%= form_with(model: @article) do |f| %> 
        <%= f.label :title %>
        <%= f.text_field :title %> <br/>
        <%= f.label :note %>
        <%= f.text_field :note %> <br/>
        <%= f.label :Body %>
        <%= f.text_area :body, size: "60x10" %> <br/>
        <%= f.label :Tag %>
        <%= f.text_field :tag_list %><br /><br />
        <%= f.submit %> <br/>
    <% end %>
<div>

app/views/articles/index.html.erb
<!--
<div>
    <% @article.each do |t| %>

        <h5>Title :</h5>
        <%= t.title %> 
        <h5>Body :</h5>
        <%=t.body%> <br/>
        <%= link_to "Show", article_path(t.id)%> <br/>
        <%= link_to "Edit",edit_article_path(t.id)  %> <br/>
        <%= link_to 'Delete' , articles_delete_path(t.id),
        method: :delete,
        data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %> <br/>
    <%end%>


        <%=link_to "Create a new Article", new_article_path, class: "new_article" %>

</div> 
      <div align="right">
      <ul class="nav justify-content-end">
      <% if current_user %>
      
      <li class="nav-item"><%= link_to "Profile", users_show_path(current_user)%> <br/></li>
      <% else %>
      <li class="nav-item"> 
      <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <li class="nav-item">
      <%= link_to "Sign In", new_user_session_path %>
      </li>

<% end %>
</ul>
</div>
-->

<div class="container">
<button type="button" class="btn btn-primary">
  Articles Listing <span class="badge badge-light" style="color:red"><%= @article.size%></span>
</button>
</div>
<div class= "container-fluid" style="background-color: #e3f2fd;">
<table class="table" >
  <tr>
    <th scope="col">Title</th>
    <th>Short Note</th>

  </tr>
  <% @article.each do |t| %>
  <tr >
    <td><%= t.title %> </td>
    <td><%=t.note%></td>
    <td class="btn btn-info"><%= link_to "Show", article_path(t.id), :class => "btn"%> </td>
    <% if t.user == current_user%>
    <td class="btn btn-primary"><%= link_to "Edit",edit_article_path(t.id), :class => "btn" %></td>
    <td class="btn btn-danger"><%= link_to "Delete", articles_delete_path(t.id),
        method: :delete,
        data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } ,:class => "btn"%>
    </td>
    <% end %>
  </tr>
  <%end%>
  </table>
 </div>
 <% if current_user %>
 <p class="btn btn-success">
   <%= link_to "Create a new Article", new_article_path, class: "new_article",:class => "btn" %>
</p>
<% end %>

app/views/articles/new.html.erb
<div>
    <h2>Article Form</h2> <br/>

    <%= form_with(model: @article) do |f| %> 
        <%= f.label :title %>
        <%= f.text_field :title %> <br/>
         <%= f.label :note %>
        <%= f.text_field :note %> <br/>
        <%= f.label :Body %>
        <%= f.text_area :body, size: "60x10" %> <br/> <br/>
        <%= f.label :tag_list %><br />
        <%= f.text_field :tag_list %>
        <%= f.submit %> <br/>
    <% end %>
</div>

app/views/articles/show.html.erb
<div>
    <h3>Title : </h3>
        <%= @article.title%> <br/>
     <h3>Short Note : </h3>
        <%= @article.note%> <br/>


    <h3>Content :</h3>
        <%= @article.body %> <br/><br/>
    <div class="">
        <button class="btn btn-primary" type="button"><%= link_to "Next >>",article_path(@article.next), :class => "btn" %></button>
        <% if current_user %>
        <button class="btn btn-outline-danger" ><%= link_to "Delete", articles_delete_path(@article.id),method: :delete, :class => "btn" %> <br/></button>
        <button class="btn btn-outline-warning" type="button"><%= link_to "Edit", edit_article_path(@article.id), :class => "btn" %></button>
        <% end %>
    </div>

        
        <p>
        Tags:
        <% @article.tags.each do |tag| %>
       <button class="badge bg-outline-dark" ><%= link_to tag.name.upcase, tag_path(tag.id), :class => "btn"%> </button>
        <% end %>
        </p>    

    <h3>Comments (<%= @article.comments.size %>) </h3>

        <%= render partial: 'comments/comment', collection: @article.comments %>
        <%= render partial: 'comments/form', locals: {article: @article } %>

    <%= link_to "<< Back to Articles List" , articles_path, :class => "btn" %> <br/>

</div>