config/routes.rb
Rails.application.routes.draw do

    root 'articles#index'
    

    resources :articles, except: [:destroy] do
        resources :comments#, only: [:create]
    end
    delete 'articles/:id/delete' => 'articles#destroy', as: 'articles_delete'
    get '/articles/:id/delete' => 'articles#destroy'

    resources :tags

    devise_for :users, controllers: {
        registrations: 'users/registrations'
    }


    get 'my_profile' => 'users#show', as: 'users_show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open-Post</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
    crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      div {
        width: 70%;
        margin: auto;
      }
    </style>

  </head>


  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background-color: #e3f2fd;">


      <span class="navbar-brand mb-0 h1">Open-Post</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home",articles_path , :class=>"nav-link"%>
          </li>
          <li class="nav-item">
            <%=link_to "Tags",tags_path, :class=>"nav-link"%>
          </li>         
        </ul>
               
      </div>
    <div class="btn-group" >
    <% if user_signed_in? %>
      <div class="btn btn-light position-absolute top-0 start-80 end-0"> <%= button_to(
                    "Log Out",
              destroy_user_session_path,
              method: :delete, 
             :class => "btn")%> 
      </div>
   <button type="button" class="btn btn-light position-absolute top-0 end-0"> 
            <%= link_to "Profile", users_show_path, :class => "btn" %>
          
      </button>

    <% else %>
      <button type="button" class="btn btn-light position-relative">   
            <%= link_to "Sign Up", new_user_registration_path, :class => "btn" %>
          
          
        
      </button>
      <button type="button" class="btn btn-light position-relative"> 
        
            <%= link_to "Sign In", new_user_session_path, :class => "btn" %>
          
      </button>
     <%end%>
    </div>
  </nav>



    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

      <div>
      <%= notice if notice%>
      <%= alert if alert %>
      <%= yield %>
      </div>

    <div class="container my-5">
      <footer class="bg-light text-center text-white">
        <div class="container p-4 pb-0">
          <section class="mb-4">
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #3b5998;"
              href="#!"
              role="button"
              >Top</a>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 01, 0.3);">
          © 2022 | Website Under Development : 
          <a class="text-white" href="">Open-Post.xyZ</a>
        </div>
      </footer> 
     </div>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
     crossorigin="anonymous">

  </body>
</html>